CI setup

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -1,25 +1,48 @@
 name: build-image
-
 on:
-  workflow_dispatch:
-   inputs:
-      python_version:
-        description: 'Python base Docker image tag (https://hub.docker.com/_/python/tags)'
-        required: true
-        default: '3.10-slim'
-
-env:
-  IMAGENAME: rrsync
-  PYTHON_VERSION: ${{ github.event.inputs.alpine_version || vars.PYTHON_VERSION }}
+  push:
+    tags:
+      - '*'
 
 jobs:
+  validate:
+    runs-on: ubuntu-latest
+    env:
+      TAG_PATTERN: "^([0-9]+)\.([0-9]+)-alpine-(.*)$"
+    outputs:
+      major: ${{ steps.decode.outputs.major }}
+      minor: ${{ steps.decode.outputs.minor }}
+      alpine-version: ${{ steps.decode.outputs.alpine-version }}
+      is-valid: ${{ steps.decode.outputs.is-valid }}
+    steps:
+      - name: Tag decoding and validation
+        id: decode
+        run: |
+          TAG="${{ github.ref_name }}"
+          echo "Tag received: $TAG"
+          if [[ $TAG =~ $TAG_PATTERN ]]; then
+            echo "major=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
+            echo "minor=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
+            echo "alpine-version=${BASH_REMATCH[3]}" >> $GITHUB_OUTPUT
+            echo "is-valid=true" >> $GITHUB_OUTPUT
+          else
+            echo "is-valid=false" >> $GITHUB_OUTPUT
+            echo "::error::Tag '$TAG' does not match the pattern "
+            exit 1
+          fi
+
   build-image:
+    needs: validate
+    if: needs.validate.outputs.is-valid == 'true'
     runs-on: ubuntu-latest
     steps:
       - name: Set version value
         id: version
         run: |
-          echo "value=${PYTHON_VERSION}.$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_OUTPUT
+          echo "Major:    ${{ needs.validate.outputs.major }}"
+          echo "Minor:    ${{ needs.validate.outputs.minor }}"
+          echo "Alpine:   ${{ needs.validate.outputs.alpine-version }}"
+          echo "value=${{ needs.validate.outputs.major }}.${{ needs.validate.outputs.minor }}-alpine-${{ needs.validate.outputs.alpine-version }}" >> $GITHUB_OUTPUT
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
@@ -35,18 +58,19 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-      # - name: Login to DockerHub
-      #   uses: docker/login-action@v2
-      #   with:
-      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
-      #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
       - name: Build and push
         uses: docker/build-push-action@v6
         with:
           context: "{{defaultContext}}:context"
           build-args: |
-            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
+            ALPINE_VERSION=${{ needs.validate.outputs.alpine-version }}
           push: true
           platforms: linux/amd64
           tags: |
             ghcr.io/${{ github.repository }}:${{ steps.version.outputs.value }}
+            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ steps.version.outputs.value }}
